# Generated by Django 4.2.13 on 2026-06-21 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_member_has_voted_alter_member_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('ward', models.CharField(blank=True, max_length=255)),
                ('polling_station', models.CharField(blank=True, max_length=255)),
                ('rider_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CanvassAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=255)),
                ('polling_station', models.CharField(blank=True, max_length=255, null=True)),
                ('target_households', models.IntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('mobilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvass_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TallyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_station', models.CharField(max_length=255)),
                ('ward', models.CharField(blank=True, max_length=255)),
                ('dcp_votes', models.IntegerField(default=0)),
                ('uda_votes', models.IntegerField(default=0)),
                ('other_votes', models.IntegerField(default=0)),
                ('total_votes_cast', models.IntegerField(default=0)),
                ('registered_voters', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tallies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('polling_station', 'submitted_by')},
            },
        ),
        migrations.CreateModel(
            name='PollingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=255)),
                ('polling_station', models.CharField(max_length=255)),
                ('checked_in', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('member', 'polling_station')},
            },
        ),
    ]
