# Generated by Django 4.2.13 on 2026-06-21 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transportrequest_canvassassignment_tallyrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBankTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('ward', models.CharField(blank=True, max_length=255)),
                ('polling_station', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Call'), ('called', 'Called'), ('unreachable', 'Unreachable')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_bank_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('kiems_failure', 'KIEMS Kit Failure'), ('bribery', 'Voter Bribery'), ('violence', 'Intimidation / Violence'), ('late_opening', 'Late Opening of Station'), ('other', 'Other Irregularity')], max_length=50)),
                ('ward', models.CharField(max_length=255)),
                ('polling_station', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('strong_dcp', 'Strong DCP'), ('leaning_dcp', 'Leaning DCP'), ('undecided', 'Undecided'), ('uda', 'Voting UDA'), ('not_voting', 'Not Voting'), ('wrong_number', 'Wrong Number / Unreachable')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='api.phonebanktarget')),
            ],
        ),
    ]
