# Generated by Django 5.0.1 on 2026-06-22 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_callrecord_id_alter_canvassassignment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencybroadcast",
            name="target_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="targeted_broadcasts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emergencybroadcast",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("ward", "Specific Wards"),
                    ("specific_people", "Specific People"),
                ],
                default="global",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emergencybroadcast",
            name="target_wards",
            field=models.JSONField(
                blank=True, help_text="List of ward names", null=True
            ),
        ),
    ]
