# Generated by Django 6.0.4 on 2026-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_transportrequest_rider_phone_alter_callrecord_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencybroadcast",
            name="target_polling_stations",
            field=models.JSONField(
                blank=True, help_text="List of polling stations", null=True
            ),
        ),
    ]
