# Generated by Django 5.0.1 on 2026-06-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_voterrecord_dob_alter_callrecord_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voterrecord",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
