# Generated by Django 5.0.1 on 2026-06-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_voterrecord_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
