# Generated by Django 6.0.4 on 2026-07-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_callrecord_id_alter_canvassassignment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="incident_images/"
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="incident_videos/"),
        ),
    ]
