# Generated by Django 6.0.4 on 2026-07-13 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_incidentreport_image_incidentreport_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_security",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ward", models.CharField(max_length=255)),
                ("polling_station", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("all_clear", "All Clear - Routine"),
                            ("crowd_building", "Crowd Building"),
                            ("tense", "Tense Situation"),
                            ("panic", "PANIC / SEND BACKUP"),
                        ],
                        default="all_clear",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "guard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
