# Generated by Django 6.0.4 on 2026-07-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_member_is_security_securitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securitylog",
            name="resolved",
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securitylog",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securitylog",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securitylog",
            name="resolution_action",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatched_police", "Dispatched Police"),
                    ("dispatched_qrt", "Dispatched QRT"),
                    ("false_alarm", "False Alarm"),
                    ("resolved_internally", "Resolved Internally"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
