# Generated by Django 6.0.4 on 2026-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_remove_securitylog_resolved_incidentreport_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="security_rank",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("guard", "Guard"),
                    ("station_commander", "Station Commander"),
                    ("ward_commander", "Ward Commander"),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
