# Generated by Django 6.0.4 on 2026-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_member_security_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_security_only",
            field=models.BooleanField(default=False),
        ),
    ]
