// Ol Kalou Constituency, Nyandarua County
// Source: IEBC 2022 General Election voter register
// 5 wards | 142 polling stations total | 72,997 registered voters

export const wardsWithCenters = [
  {
    id: "olkalou_kanjuiri",
    name: "Kanjuiri Range",
    label: "Kanjuiri Range Ward",
    centers: [
      "Rutara Primary",
      "Kangathia Primary",
      "Ngorika Primary",
      "Ciira Primary",
      "Kanjuiri Primary",
      "Kirathimo Primary",
      "Wiyumiririe Primary",
      "Tumaini Secondary",
      "Nyaituga Primary",
      "Kihoto Primary",
      "Murindati Primary",
      "Kanjau Mutarakwa Nursery",
      "Kahigu Primary",
      "Harambee Nursery School",
      "Tumaini Primary School",
      "Kio Primary School",
      "Wanjura Primary",
    ],
  },
  {
    id: "olkalou_rurii",
    name: "Rurii",
    label: "Rurii Ward",
    centers: [
      "Rurii Polytechnic",
      "Passenga Primary",
      "Githunguri Primary",
      "Huhoini Primary",
      "Mugumo Primary",
      "Mukindu Primary",
      "Matuura Primary",
      "Siranga Primary",
      "Manyatta Primary",
      "Mugathika Primary",
      "St. Thomas Primary",
      "Umoja Primary School",
      "Rurii Primary School",
      "Kianduba Primary School",
      "Kahonge Primary School",
      "Marani Primary School",
      "JM Hospital Nursery School",
    ],
  },
  {
    id: "olkalou_mirangine",
    name: "Mirangine",
    label: "Mirangine Ward",
    centers: [
      "Nyakiambi Primary",
      "CCM Dundori Primary",
      "Gituamba Primary",
      "Mathakwa Primary",
      "Githima Primary",
      "Matunda Primary",
      "Nyandundo Primary",
      "Mirangine Primary",
    ],
  },
  {
    id: "olkalou_karau",
    name: "Karau",
    label: "Karau Ward",
    centers: [
      "A.C. Ol Kalou Primary School",
      "Mawingo Primary School",
      "Kagaa Primary School",
      "Muiri Primary School",
      "Karugutu Primary School",
      "Gachwe Primary School",
      "Munyeki Primary School",
      "Kirimaini Primary School",
      "Mundi Primary School",
    ],
  },
  {
    id: "olkalou_kaimbaga",
    name: "Kaimbaga",
    label: "Kaimbaga Ward",
    centers: [
      "Mihuti Primary School",
      "Huruma Primary School",
      "Simba Primary School",
      "Gichungo Primary School",
      "Kandutura Primary School",
      "Kieni Primary School",
      "Kamande Primary School",
      "Rumathi Primary School",
      "Kiganjo Primary School",
      "Mumbi Primary School",
      "Hospital Primary School",
      "Githima Nursery School",
      "Kaimbaga Primary School",
    ],
  },
];
